name: ServerEssentials
version: 1.82.1
main: me.rocketmankianproductions.serveressentials.ServerEssentials
api-version: 1.16
authors: [ RocketManKian ]
description: A Plugin for all Server Owners!
softdepend: [PlaceholderAPI, DiscordSRV, DiscordSRV-Staff-Chat, AcceptTheRules, HuskHomes, LibsDisguises] # Plugins that load before ServerEssentials
loadbefore: [Essentials]
commands:
  se:
    description: Server Essentials Root Command
    usage:
  discord:
    description: Discord
    aliases: [dc]
  website:
    description: Website
    aliases: [web,site]
  youtube:
    description: YouTube
    aliases: [yt]
  twitch:
    description: Twitch
  jump:
    description: Bounce like a bunny
  rules:
    description: Rules Command
  hurt:
    description: Hurt the Player
  playtime:
    description: Shows Playtime
  setspawn:
    description: Sets the spawn
  tutorial:
    description: Teleports you to newbie spawn
  spawn:
    description: Teleports you to spawn
  sendspawn:
    description: Teleports a player to Spawn
  deletespawn:
    description: Deletes the spawn
    aliases: [delspawn]
  sethome:
    description: Sets Your Home
  home:
    description: Teleports you to Home
  deletehome:
    description: Deletes your Home
    aliases: [delhome]
  teleport:
    description: Teleport Function
    aliases: [tp]
  tphere:
    description: Teleport Here Function
    aliases: [teleporthere]
  teleportall:
    description: Teleport Function
    aliases: [tpall]
  tpa:
    description: Teleport Request
  tpahere:
    description: Teleport Here Request
  tpaccept:
    description: Teleport Accept
  tpdeny:
    description: Teleport Deny
  tptoggle:
    description: TPToggle Command
  heal:
    description: Heal
  feed:
    description: Feed
  announce:
    description: Announce
    aliases: [bc,broadcast]
  invsee:
    description: Invsee Command
  gamemode:
    description: Gamemode Command
    aliases: [gm]
  creative:
    description: Creative Command
    aliases: [c, 1]
  survival:
    description: Survival Command
    aliases: [s, 0]
  adventure:
    description: Adventure Command
    aliases: [a, 2]
  spectator:
    description: Spectator Command
    aliases: [3]
  gmc:
    description: Creative Command
  gms:
    description: Survival Command
  gmsp:
    description: Spectator Command
  gma:
    description: Adventure Command
  fly:
    description: Fly Command
  kill:
    description: Kill Command
    aliases: [suicide]
  msg:
    description: Message Command
    aliases: [message]
  msgtoggle:
    description: Message Toggle Command
  reply:
    description: Reply Command
    aliases: [r]
  craft:
    description: Craft Command
  enderchest:
    description: Enderchest Command
    aliases: [ec]
  setwarp:
    description: Setwarp Command
  warp:
    description: Setwarp Command
  deletewarp:
    description: Deletewarp Command
    aliases: [delwarp]
  repair:
    description: Repair Command
    aliases: [fix]
  sunrise:
    description: Sunrise Command
    aliases: [dawn]
  day:
    description: Day Command
  sunset:
    description: Sunset Command
    aliases: [dusk]
  midnight:
    description: Midnight Command
  sun:
    description: Clear Weather Command
  thunder:
    description: Storm Command
  storm:
    description: Storm Command
  vanish:
    description: Vanish Command
    aliases: [v]
  test:
    description: Test Command
  test motd:
    description: Test Motd Command
  test join:
    description: Test Join Command
  test leave:
    description: Test Leave Command
  test welcome:
    description: Test Welcome Command
  test permission:
    description: Test Permission Command
  clear:
    description: Clear Command
  god:
    description: God Command
    aliases: [godmode]
  hat:
    description: Hat Command
  sendhome:
    description: Send Home Command
  listhomes:
    description: List Home Command
  tpacancel:
    description: TPA Cancel Command
  rename:
    description: Rename Command
  lore:
    description: Lore Command
  speed:
    description: Speed Command
  report:
    description: Report Command
  reportbug:
    description: Report Bug Command
  clearchat:
    description: Clear Chat Command
    aliases: [cc]
  sendwarp:
    description: Send Warp Command
  socialspy:
    description: Social Spy Command
  staffchat:
    description: Staff Chat Command
    aliases: [sc, ac, adminchat]
  trash:
    description: Trash Command
  back:
    description: Back Command
  convert:
    description: Convert Command
  sudo:
    description: Sudo Command
  whois:
    description: WhoIs Command
    aliases: [checkaccount, checkplayer, playerinfo]
  ping:
    description: Ping Command
permissions:
  se.all:
    description: "Gives access to all commands."
    default: op
    children:
      se.reload: true
      se.website: true
      se.discord: true
      se.youtube: true
      se.twitch: true
      se.rules: true
      se.hurt: true
      se.playtime: true
      se.version: true
      se.setspawn: true
      se.spawn: true
      se.spawn.others: true
      se.deletespawn: true
      se.alert: true
      se.silentjoin: true
      se.sethome: true
      se.sethome.unlimited: true
      se.home: true
      se.home.others: true
      se.listhomes: true
      se.sendhome: true
      se.deletehome: true
      se.deletehome.others: true
      se.tpa: true
      se.tpaccept: true
      se.tpdeny: true
      se.teleport: true
      se.teleport.coords: true
      se.tpall: true
      se.silenttp: true
      se.info: true
      se.heal: true
      se.feed: true
      se.announce: true
      se.tptoggle: true
      se.invsee: true
      se.invsee.others: true
      se.gamemode.creative: true
      se.gamemode.survival: true
      se.gamemode.adventure: true
      se.gamemode.spectator: true
      se.fly: true
      se.fly.others: true
      se.tpahere: true
      se.kill: true
      se.message: true
      se.reply: true
      se.msgtoggle: true
      se.craft: true
      se.enderchest: true
      se.enderchest.others: true
      se.setwarp: true
      se.setwarp.block: true
      se.warp: true
      se.sendwarp: true
      se.deletewarp: true
      se.repair: true
      se.time: true
      se.vanish: true
      se.test: true
      se.clear: true
      se.god: true
      se.hat: true
      se.tpacancel: true
      se.rename: true
      se.lore: true
      se.speed: true
      se.speed.all: true
      se.speed.others: true
      se.reportuser: true
      se.reportbug: true
      se.reportnotification: true
      se.clearchat: true
      se.warps.all: true
      se.socialspy: true
      se.staffchat: true
      se.trash: true
      se.back: true
      se.back.bypass: true
      se.teleport.bypass: true
      se.convert: true
      se.sudo: true
      se.whois: true
      se.ping: true
      se.afk: true
  se.reload:
    description: "Gives access to the /se reload command."
    default: false
  se.website:
    description: "Gives access to the /website command."
    default: false
  se.discord:
    description: "Gives access to the /discord command."
    default: false
  se.youtube:
    description: "Gives access to the /youtube command."
    default: false
  se.twitch:
    description: "Gives access to the /twitch command."
    default: false
  se.rules:
    description: "Gives access to the /rules command."
    default: false
  se.hurt:
    description: "Gives access to the /hurt command."
    default: false
  se.playtime:
    description: "Gives access to the /playtime command."
    default: false
  se.version:
    description: "Gives access to the /seversion command"
    default: false
  se.setspawn:
    description: "Gives access to the /setspawn command"
    default: false
  se.spawn:
    description: "Gives access to the /spawn command"
    default: false
  se.spawn.others:
    description: "Gives access to the teleporting other players to Spawn"
    default: false
  se.deletespawn:
    description: "Gives access to /deletespawn"
    default: false
  se.alert:
    description: "Gives Update Alerts"
    default: false
  se.silentjoin:
    description: "Silent Join"
    default: false
  se.sethome:
    description: "Set Home"
    default: false
  se.home:
    description: "Teleport To Home"
    default: false
  se.deletehome:
    description: "Deletes Home"
    default: false
  se.deletehome.others:
    description: "Deletes Other Player's Homes"
    default: false
  se.teleport:
    description: "Teleport Command"
    default: false
  se.teleport.coords:
    description: "Teleport Coords Command"
    default: false
  se.tpall:
    description: "Teleport All Command"
    default: false
  se.info:
    description: "SE Info Command"
    default: false
  se.silenttp:
    description: "SilentTP Command"
    default: false
  se.sethome.unlimited:
    description: "Unlimited Sethome Command"
    default: false
  se.tpa:
    description: "Teleport Request"
    default: false
  se.tpaccept:
    description: "Teleport Accept"
    default: false
  se.tpdeny:
    description: "Teleport Deny"
    default: false
  se.tptoggle:
    description: "Teleport Toggle"
    default: false
  se.heal:
    description: "Heal Command"
    default: false
  se.feed:
    description: "Feed Command"
    default: false
  se.announce:
    description: "Announce Command"
    default: false
  se.invsee:
    description: "Invsee Command"
    default: false
  se.gamemode.creative:
    description: "Creative Command"
    default: false
  se.gamemode.survival:
    description: "Survival Command"
    default: false
  se.gamemode.spectator:
    description: "Spectator Command"
    default: false
  se.gamemode.adventure:
    description: "Adventure Command"
    default: false
  se.fly:
    description: "Fly Command"
    default: false
  se.fly.others:
    description: "Fly Others Command"
    default: false
  se.tpahere:
    description: "Tpahere Command"
    default: false
  se.kill:
    description: "Kill Command"
    default: false
  se.message:
    description: "Message Command"
    default: false
  se.reply:
    description: "Message Command"
    default: false
  se.msgtoggle:
    description: "MSG Toggle Command"
    default: false
  se.craft:
    description: "Craft Command"
    default: false
  se.enderchest:
    description: "Enderchest Command"
    default: false
  se.enderchest.others:
    description: "Enderchest Others Command"
    default: false
  se.setwarp:
    description: "Setwarp Command"
    default: false
  se.warp:
    description: "Warp Command"
    default: false
  se.deletewarp:
    description: "Delete Warp Command"
    default: false
  se.repair:
    description: "Repair Command"
    default: false
  se.time:
    description: "Time Command"
    default: false
  se.vanish:
    description: "Vanish Command"
    default: false
  se.test:
    description: "Test Command"
    default: false
  se.clear:
    description: "Clear Command"
    default: false
  se.god:
    description: "God Command"
    default: false
  se.hat:
    description: "Hat Command"
    default: false
  se.home.others:
    description: "Home Others Command"
    default: false
  se.sendhome:
    description: "Send Home Command"
    default: false
  se.listhomes:
    description: "List Homes Command"
    default: false
  se.tpacancel:
    description: "TPA Cancel Command"
    default: false
  se.rename:
    description: "Rename Command"
    default: false
  se.lore:
    description: "Lore Command"
    default: false
  se.speed:
    description: "Speed Command"
    default: false
  se.speed.all:
    description: "Speed All Command"
    default: false
  se.speed.others:
    description: "Speed Others Command"
    default: false
  se.reportbug:
    description: "Report Bug Command"
    default: false
  se.reportuser:
    description: "Report User Command"
    default: false
  se.reportnotification:
    description: "Report Notification"
    default: false
  se.clearchat:
    description: "Clear Chat Command"
    default: false
  se.warps.all:
    description: "All Warps Permission"
    default: false
  se.sendwarp:
    description: "Send Warp Command"
    default: false
  se.socialspy:
    description: "Social Spy Permission"
    default: false
  se.invsee.others:
    description: "Invsee Others Permission"
    default: false
  se.staffchat:
    description: "StaffChat Command"
    default: false
  se.trash:
    description: "Trash Command"
    default: false
  se.back:
    description: "Back Command"
    default: false
  se.back.bypass:
    description: "Back Bypass Permission"
    default: false
  se.teleport.bypass:
    description: "Teleport Bypass Permission"
    default: false
  se.convert:
    description: "Convert Command Permission"
    default: false
  se.setwarp.block:
    description: "Setwarp Block Command Permission"
    default: false
  se.sudo:
    description: "Sudo Command Permission"
    default: false
  se.whois:
    description: "Whois Command Permission"
    default: false
  se.ping:
    description: "Ping Command Permission"
    default: false
  se.afk:
    description: "AFK Command Permission"
    default: false